### ISSUE TITLE
Battery extension

### ISSUE THREAD

**Issue by Rezenders** [kas-lab/suave#149]
- [ ] Add argument to launchfile to indicate if battery should be used
- [ ] If battery is supposed to be used, the robot mission should be considered as aborted when the battery is below a certain threshold. This can be analyzed in the mission node, e.g. https://github.com/kas-lab/suave/blob/main/suave_missions/suave_missions/time_constrained_mission.py

**Comment by QMissinne** [comment]
argument added to launchfile as:
- none (default)
- battery_constraint (at threshold value, abort mission)

Next step is to implement the functionality of the battery.

**Comment by QMissinne** [comment]
to implement functionality : 
instantiate BatteryMonitor() in inspection_mission. From this use battery_level variable and follow the structure of time_monitor_cb (in time_constrained_mission).

**Comment by QMissinne** [comment]
Instantiating class is not the right approach.

Instead, subscribe to diagnostics topic and read the battery_level from there. Constraint should remain the same.
