### ISSUE TITLE
keep information about inspected distance in log

### ISSUE THREAD

**Issue by tobiaswjohn** [kas-lab/suave#151]
In the past, the ROS log contained a line as
`[time_constrained_mission-1] [INFO] [1701088443.108675294] [mission_node]: Distance inspected: 49.61215591430664 meters`

the current version only provides the time for searching the pipeline and the mission time. 
I know that the inspection length is in the results file, but I would appreciate it, if it would also (remain) part of the log. (as my evaluation is based on them and it saves me effort...)

**Comment by Rezenders** [comment]
Done at 21dc6a0c568212cf995d7e3f8cc9a0669316c824
