### ISSUE TITLE
Measure time elapsed to perform adaptation

### ISSUE THREAD

**Issue by Rezenders** [kas-lab/suave#152]
Measure the time elapsed to perform adaptation. 
For example, when a thruster component fails, how long does it take for the robot to switch to the recovery mode?
Or when a water visibility constraint is violated, how long does it take for the robot to switch altitude?
How long does it take to switch from the search pipeline action to the inspection pipeline action?

**Comment by QMissinne** [comment]
Initial approach: 

Implement ParameterEventHandler class according to:

https://docs.ros.org/en/rolling/Tutorials/Intermediate/Monitoring-For-Parameter-Changes-Python.html
