### ISSUE TITLE
change naming scheme for results file

### ISSUE THREAD

**Issue by tobiaswjohn** [kas-lab/suave#153]
The naming of the result files (.csv) is a bit annoying for me.
the format is `[...]_DD_MM_YY_HH_MM_[...].csv` but I think `[...]_YY_MM_DD_HH_MM_[...].csv` would be better, as sorting the files by name would also sort them by time. 
Just a little enhancement :)

**Comment by Rezenders** [comment]
Done at bfaff8297c47f6e35f09cd8345f55584f768f0d5
